### PR TITLE
Support Racket on Chez Scheme

### PR DESCRIPTION
**Pull request by LiberalArtist**
Use the FFI instead of depending on Racket BC's C API.

(But we still build a shared C library, because I'm not sure
about the portability of the `struct termios` type.)

Closes https://github.com/tonyg/racket-ansi/issues/6

This follows basically the same strategy as <https://github.com/tonyg/racket-unix-signals/pull/2>. The interactive tests are passing for me.

### CODE REVIEW

**Comment by LiberalArtist** [comment]
I see that https://github.com/jeapostrophe/raart depends on `ansi/private/tty-raw-extension` directly, so I've made that the file name again, even though it isn't actually an "extension" any more.

**Comment by arpunk** [comment]
Any news on this?

**Comment by samth** [comment]
ping @tonyg

**Comment by tonyg** [comment]
Thanks very much!

**Pull request merged**
